name: cypress tests

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 2 * * *'  # runs every day at 2am UTC

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install dependencies
        run: npm install

      - name: run cypress tests
        run: npx cypress run
